In [1]:
import pandas as pd

In [29]:
# 1.- Crear un programa que sea capaz de leer el archivo videojuegos.csv,
# luego sacar el promedio de los precios y el promedio de la calificación.

def calcularPromedios(nomArchivo):
    # Cargando el archivo xlsm como si fuera un csv
    df = pd.read_excel(nomArchivo, engine='openpyxl', header=None)

    # Dividiendo la columna 0 en varias columnas
    df = df[0].str.split(',', expand=True)

    # Renombrando las columnas
    df.columns = df.iloc[0]

    # Eliminando la primera fila (encabezado)
    df = df[1:]

    # Convirtiendo las columnas 'Calificacion' y 'Precio' a float
    df['Calificacion'] = df['Calificacion'].astype(float)
    df['Precio'] = df['Precio'].astype(float)

    # Calculando el promedio de los precios y de la calificación
    promedio_precios = df['Precio'].mean()
    promedio_calificacion = df['Calificacion'].mean()

    return promedio_precios, promedio_calificacion

# Ejemplo de uso
precio_promedio, calificacion_promedio = calcularPromedios('videojuegos1.csv.xlsm')
print('El precio promedio es: ', precio_promedio)
print('La calificación promedio es: ', calificacion_promedio)

El precio promedio es:  788.695
La calificación promedio es:  94.83333333333333

         Nombre,Calificacion,Precio
0                   Cuphead,100,180
1              Doom eternal,99,1400
2        Horizon Zero Dawn,90,450.7
3  Resident Evil 2 Remake,95,450.88
4    Super Mario Odyssey,90,1700.05

In [33]:
# a) La función juegosConsolas(nomArchivo, categoria, decada) que recibe el
# nombre del archivo con la información de los videojuegos, una categoría y
# número de cuatro dígitos representando una década de años. La función
# retorna una tupla con 2 elementos. El primer elemento es la lista con los
# valores únicos de todos los juegos de esa década para esa categoría. El
# segundo elemento es la lista con valores únicos de todas las consolas que
# tienen juegos para esa década y categoría.

def juegosConsolas(nomArchivo, categoria, decada):
    # Cargando el archivo xlsm como si fuera un csv
    df = pd.read_excel(nomArchivo, engine='openpyxl', header=None)

    # Dividimos la columna 0 en varias columnas
    df = df[0].str.split(',', expand=True)

    # Establecemos la primera fila como encabezado
    df.columns = df.iloc[0]
    df = df[1:]

    # Renombramos las columnas
    df.columns = ['Nombre', 'Año', 'Consola', 'Calificación', 'Categoría', 'Tags']

    # Convirtiendo la columna 'Año' a int
    df['Año'] = df['Año'].astype(int)
    
    #Extraer década
    decada = int(str(decada)[-2:])

    # Filtrando por categoría y década
    filtered_df = df[(df['Categoría'] == categoria) & (df['Año'] >= decada) & (df['Año'] < decada + 10)]

    # Obteniendo los valores únicos de juegos y consolas
    juegos_unicos = filtered_df['Nombre'].unique().tolist()
    consolas_unicas = filtered_df['Consola'].unique().tolist()

    return (juegos_unicos, consolas_unicas)

# Ejemplo 
print(juegosConsolas('videojuegos2.csv.xlsm', 'RPG', 1980))

(['The Legend of Zelda', 'Curse of Ra'], ['NES', 'Commodore PET'])

In [44]:
# b) La función crearMatriz(nomArchivo, categoria, decada) que recibe el
# nombre del archivo con la información de los videojuegos, el nombre de una
# categoría de videojuegos y un número de cuatro dígitos representando una
# década de años. La función deberá leer el archivo y retorna una matriz donde
# las filas representan los juegos de categoría para la década , las columnas
# representan las consolas que tienen juegos de categoría para la década y las
# celdas son las calificaciones de cada juego para cada consola. Si un juego no
# existe para una consola, su calificación deberá ser cero (0).


import numpy as np

# Función para dividir los datos
def split_data(row):
    split_row = row[0].split(',')
    nombre = split_row[0]
    año = int(split_row[1])
    consola = ','.join(split_row[2:-2])
    calificacion = float(split_row[-2])
    categoria = split_row[-1]
    return pd.Series([nombre, año, consola, calificacion, categoria])

def crearMatriz(nomArchivo, categoria, decada):
    # Cargando el archivo xlsm
    df = pd.read_excel(nomArchivo, engine='openpyxl')

    # Aplicamos la función para dividr los datos
    df = df.apply(split_data, axis=1)
    df.columns = ['Nombre', 'Año', 'Consola', 'Calificación', 'Categoría']

    #Extraer década
    decada = int(str(decada)[-2:])
    # Filtramos por categoría y década
    filtered_df = df[(df['Categoría'] == categoria) & (df['Año'] >= decada) & (df['Año'] < decada + 10)]

    # Creamos la matriz de juegos y consolas
    juegos = filtered_df['Nombre'].unique().tolist()
    consolas = filtered_df['Consola'].unique().tolist()

    matriz = pd.DataFrame(np.zeros((len(juegos), len(consolas))), index=juegos, columns=consolas)

    # Rellenando la matriz con las calificaciones
    for index, row in filtered_df.iterrows():
        matriz.loc[row['Nombre'], row['Consola']] = row['Calificación']

    return matriz

# Ejemplo
print(crearMatriz('videojuegos2.csv.xlsm', 'RPG', 1980))

                     Famicom,Disk System  NES  Commodore PET
The Legend of Zelda                  3.5  4.3            0.0
Curse of Ra                          0.0  0.0            3.0

,0,1,2,3,4
0,"Nombre,AÃ±o,Consola,Calificacion,Tags(separado...",),NaN,NaN,NaN
1,"The Legend of Zelda,86,Famicom,Disk System,3.5...",Link,Zelda,Hyrule,Triforce
2,"Double Dragon,87,Arcade,3.7,Beat-'em up",Billy,Jimmy,PuÃ±ete,NaN
3,"The Legend of Zelda,88,NES,4.3,RPG",Link,Zelda,Hyrule,Triforce
4,"Halo 5: Guardians,15,Xbox One,4,FPS",Master Chief,Cortana,Covenant,NaN